name: Trigger Org-Level Policy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-org-policy-scan:
    uses: sanjeetkumaritoutlook/reusable-workflows/.github/workflows/policy-scan.yml@main
    with:
      check_license: true
      check_readme: true
